### ISSUE TITLE
[map]: cannot parse the memory map of 1804

### ISSUE THREAD

**Issue by john-peterson** [ouadev/proc_maps_parser#9]
Does it work in Ubuntu lunar?

I just created a clean vm and got this

```
build/map 1804
pmparser : fgets failed, Success
[map]: cannot parse the memory map of 1804
```

The PID is for the running bash proc from

```
ps|grep bash

**Comment by MorningLightMountain713** [comment]
Same - ubuntu 22.04

**Comment by Elkozel** [comment]
I got the same issue
# Fix
In `pmparser.c` change:
```
if (fgets(buf,PROCMAPS_LINE_MAX_LENGTH,file) == NULL){
```
with 
```
if (fgets(buf,PROCMAPS_LINE_MAX_LENGTH,file) == NULL && ferror(file) != 0){
```

# Explanation
The problem is with the `fgets` call, which returns a null pointer here:
```
if (fgets(buf,PROCMAPS_LINE_MAX_LENGTH,file) == NULL){
	fprintf(stderr,"pmparser : fgets failed, %s\n",strerror(errno));
```
However, fgets can return a null pointer when there is no error, as stated in the [reference](https://cplusplus.com/reference/cstdio/fgets/):

> On success, the function returns str.
> If the end-of-file is encountered while attempting to read a character, the eof indicator is set ([feof](https://cplusplus.com/feof)). If this happens before any characters could be read, the pointer returned is a null pointer (and the contents of str remain unchanged).
> If a read error occurs, the error indicator ([ferror](https://cplusplus.com/ferror)) is set and a null pointer is also returned (but the contents pointed by str may have changed).

So, we just need to cover the case where `fgets` returns a null pointer, however no error has occurred:
```
if (fgets(buf,PROCMAPS_LINE_MAX_LENGTH,file) == NULL && ferror(file) != 0){
```

**Comment by ouadev** [comment]
fixed
